name: Build (Android + Shared iOS)

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Build Android
        run: ./gradlew :androidApp:assembleDebug :shared:build

  ios-shared:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Compile shared for iOS
        run: ./gradlew :shared:assemble
