name: Build (Android + Shared iOS)

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - name: Warm Gradle
        run: ./gradlew help
      - name: Build Android + shared
        run: ./gradlew :androidApp:assembleDebug :shared:build

  ios-shared:
    # build iOS only on main or when manually triggered
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - name: Build KMP for iOS (sim arm64 only)
        run: ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64
